---
services:
   piedisabler:
     
      container_name: "piedisable"
      stdin_open: true
      tty: true
      ports:
         - "80:8080"
         - "25565:25566"
      restart: unless-stopped
      environment:
         GX_USERNAME: "auto_detect" # If it doesn't auto-detect, add it yourself
         GX_SESSIONID: "" # Add this or else PieSegic may instaban you.
         BOT_TOKEN: "" # Your discord bot token, if you are running a discord based cheat.
         DISCORD_BOT: "false" # Enter true if you wish to enter a token.
         WEBSERVER: "true" # Do not disable unless you are using a vpn
         GX_PORT: 25565
         WEBUI_PORT: 8080
